import { readNotificationState, writeNotificationState, NOTIFICATION_TYPES, setPortalBanner, getPortalBanner, clearPortalBanner } from "../../data/admin/notifications.js";
import { formatDateTime, escapeHtml } from "../common.js";
import { auditAction, bootAdminShell, toast } from "./shell.js";

const shell = bootAdminShell({ active: "notifications", title: "Pranešimų valdymas" });
if (shell.allowed) {
  let state = readNotificationState();
  const modeLabel = { auto: "Automatiškai", approve: "Patvirtinti prieš siuntimą" };
  function saveState(action = "Atnaujintos pranešimų taisyklės") { writeNotificationState(state); auditAction(action, "Pranešimų valdymas", "Išsaugota"); }
  function renderRules() { const sites = ["Visos stotelės", "KA-03", "KA-05", "KA-07"]; const parameters = ["Visi parametrai", "KD 10", "NH₃", "Bendras azotas"]; document.querySelector("#gap-rules-table").innerHTML = state.gapRules.map((rule, index) => `<tr><td><strong>${escapeHtml(rule.duration)}</strong></td><td><select class="select-field" data-rule-site="${index}" aria-label="Duomenų spragos taisyklė ${escapeHtml(rule.duration)}: taškas" style="min-height:34px">${sites.map((item) => `<option ${item === (rule.site || "Visos stotelės") ? "selected" : ""}>${item}</option>`).join("")}</select></td><td><select class="select-field" data-rule-parameter="${index}" aria-label="Duomenų spragos taisyklė ${escapeHtml(rule.duration)}: parametras" style="min-height:34px">${parameters.map((item) => `<option ${item === (rule.parameter || "Visi parametrai") ? "selected" : ""}>${item}</option>`).join("")}</select></td><td><label class="admin-switch"><input type="checkbox" data-rule-index="${index}" aria-label="Duomenų spragos taisyklė ${escapeHtml(rule.duration)}: įjungta" ${rule.enabled ? "checked" : ""}><span class="fine-print">${rule.enabled ? "Įjungta" : "Išjungta"}</span></label></td></tr>`).join(""); }
  function renderModes() { document.querySelector("#notification-modes").innerHTML = NOTIFICATION_TYPES.map(([id, label]) => `<div class="admin-rule"><div><strong>${label}</strong><p>Siuntimo sprendimas šiam įspėjimo tipui.</p></div><select class="select-field" data-mode-type="${id}" aria-label="${escapeHtml(label)}: siuntimo režimas" style="width:auto;min-height:34px"><option value="auto" ${state.modes[id] === "auto" ? "selected" : ""}>${modeLabel.auto}</option><option value="approve" ${state.modes[id] === "approve" ? "selected" : ""}>${modeLabel.approve}</option></select></div>`).join(""); }
  function renderPending() { document.querySelector("#pending-notifications").innerHTML = state.pending.length ? state.pending.map((item) => { const label = NOTIFICATION_TYPES.find(([id]) => id === item.type)?.[1] || item.type; return `<div class="admin-rule"><div><strong>${escapeHtml(item.target)}</strong><p>${escapeHtml(label)} · ${formatDateTime(item.createdAt)}</p></div><div class="admin-inline-actions"><button class="button button--primary" data-pending-action="send" data-id="${item.id}" type="button">Siųsti</button><button class="button button--secondary" data-pending-action="reject" data-id="${item.id}" type="button">Atmesti</button></div></div>`; }).join("") : `<p class="muted">Laukiančių pranešimų nėra.</p>`; }
  function renderTemplate() { const template = state.templates[document.querySelector("#template-type").value]; document.querySelector("#template-subject").value = template.subject; document.querySelector("#template-body").value = template.body; }
  renderRules(); renderModes(); renderPending();
  document.querySelector("#channel-email").checked = state.channels.email; document.querySelector("#channel-group").checked = state.channels.group; document.querySelector("#channel-banner").checked = state.channels.banner; renderTemplate();
  document.querySelector("#gap-rules-table").addEventListener("change", (event) => { const index = event.target.dataset.ruleIndex ?? event.target.dataset.ruleSite ?? event.target.dataset.ruleParameter; if (index === undefined) return; if (event.target.dataset.ruleSite !== undefined) state.gapRules[index].site = event.target.value; else if (event.target.dataset.ruleParameter !== undefined) state.gapRules[index].parameter = event.target.value; else state.gapRules[index].enabled = event.target.checked; saveState("Pakeista duomenų spragos taisyklė"); renderRules(); });
  ["email", "group", "banner"].forEach((id) => document.querySelector(`#channel-${id}`).addEventListener("change", (event) => { state.channels[id] = event.target.checked; saveState("Pakeistas pranešimų kanalas"); }));
  document.querySelector("#notification-modes").addEventListener("change", (event) => { const type = event.target.dataset.modeType; if (!type) return; state.modes[type] = event.target.value; saveState("Pakeistas siuntimo režimas"); renderModes(); });
  document.querySelector("#template-type").addEventListener("change", renderTemplate);
  document.querySelector("#template-form").addEventListener("submit", (event) => { event.preventDefault(); const type = document.querySelector("#template-type").value; state.templates[type] = { subject: document.querySelector("#template-subject").value, body: document.querySelector("#template-body").value }; saveState("Atnaujintas pranešimo šablonas",); toast("Šablonas išsaugotas."); });
  document.querySelector("#pending-notifications").addEventListener("click", (event) => { const button = event.target.closest("button[data-pending-action]"); if (!button) return; state.pending = state.pending.filter((item) => item.id !== button.dataset.id); saveState(button.dataset.pendingAction === "send" ? "Išsiųstas laukiantis pranešimas" : "Atmestas laukiantis pranešimas", button.dataset.id); renderPending(); toast(button.dataset.pendingAction === "send" ? "Pranešimas išsiųstas simuliuojant." : "Pranešimas atmestas."); });
  const currentBanner = getPortalBanner();
  if (currentBanner) { document.querySelector("#portal-banner-toggle").checked = true; document.querySelector("#portal-banner-text").value = currentBanner.text; }
  document.querySelector("#portal-banner-save").addEventListener("click", () => { const enabled = document.querySelector("#portal-banner-toggle").checked; if (enabled) { setPortalBanner(document.querySelector("#portal-banner-text").value); document.querySelector("#portal-banner-status").textContent = "Pranešimas paskelbtas viešajame pagrindiniame puslapyje."; auditAction("Paskelbtas administracijos pranešimas portale", "kms_amis_portal_banner", "Paskelbta"); toast("Pranešimas paskelbtas portale."); } else { clearPortalBanner(); document.querySelector("#portal-banner-status").textContent = "Portalo pranešimas išjungtas."; auditAction("Išjungtas administracijos pranešimas portale", "kms_amis_portal_banner", "Išjungta"); toast("Portalo pranešimas išjungtas."); } });
}
